#load local cwl
get_cwl_local <- function(file_path, format = c('cwl', 'json', 'yaml')) {

  file.extension <- file_ext(file_path)
  format <- match.arg(file.extension, format)

  if(format == 'cwl' & configr::is.yaml.file(file_path)){
    return(read_cwl_yaml(file_path))
  }

  if(format == 'cwl' && configr::is.json.file(file_path)){
    return(read_cwl_json(file_path))
  }

  if(format == 'json'){
    return(read_cwl_json(file_path))
  }else if(format == 'yaml'){
    return(read_cwl_yaml(file_path))
  }
}

inputcheck <- function(input.filepath) {
  extension <- file_ext(input.filepath)
  print(extension)
  flag.ext <- FALSE
  flag.cwl <- FALSE

  if(str_detect(input.filepath, 'bco.json')){
    flag.ext <- FALSE
    flag.cwl <- FALSE
    # print(paste('This file is junk'))
  }else if(!str_detect(input.filepath, 'bco.json')){
    flag.ext <- TRUE
    print(paste('flag.ext standing by'))
    if (extension == "yaml") {
      flow <- input.filepath %>% tidycwl::read_cwl(format = "yaml")
      cwl.version <- flow$cwlVersion
      if(!is.null(cwl.version)){
        flag.cwl <- TRUE
        print(paste('flag.cwl standing by'))
      }
    }

    if(extension %in% c("json","cwl")) {
      flow <- input.filepath %>% tidycwl::read_cwl(format = "json")
      cwl.version <- flow$cwlVersion
      if(!is.null(cwl.version)){
        # if (cwl.version %in% c("sbg:draft-2 ", "v1.0")) {
        flag.cwl <- TRUE
        print(paste('flag.cwl standing by'))
        # }
      }
    }
  }

  toggleState(id = 'next_btn_local', condition = flag.ext & flag.cwl == T)

  if (flag.ext & flag.cwl != T) {
    disable('next_btn_local')
    print(paste('Be careful not to choke on your aspirations.'))
  }else{
    print(paste('Great shot, kid! That was one in a million!'))
  }
}

#Prevent user from uploading a bco.json file which is generated by the app but not with same use as .json
observeEvent(input$upfile_local_composer, {
  inputcheck(input$upfile_local_composer$datapath)

  if(str_detect(input$upfile_local_composer$name, 'bco.json') == T){
    return(shinyalert('Unsupported File Type', "That filetype is not supported by the BCO app. Please select a .cwl, .yaml, or .json file.", type = 'error'))
  }

}, ignoreNULL = T, ignoreInit = T)

# get raw cwl
get_rawcwl_local <- eventReactive(input$upfile_local_composer, {
  cwl_out <- get_cwl_local(input$upfile_local_composer$datapath, format = file_ext(input$upfile_local_composer$datapath))
})

