get_cwl_local <- function(file_path, format = c('cwl', 'json', 'yaml')) {

  # out <- tryCatch({
  file.extension <- file_ext(file_path)
  format <- match.arg(file.extension, format)

  if(format == 'cwl' & configr::is.yaml.file(file_path)){
    return(read_cwl_yaml(file_path))
    }else if(format == 'cwl' & configr::is.json.file(file_path)){
    return(read_cwl_json(file_path))
  }else if(format == 'json'){
    return(read_cwl_json(file_path))
  }else if(format == 'yaml'){
    return(read_cwl_yaml(file_path))
  }
}
inputcheck <- function(input.filepath) {
  extension <- file_ext(input.filepath)
  flag.ext <- FALSE
  flag.cwl <- FALSE

  if (str_detect(extension, "json|cwl|yaml")) {
    print(paste("[INFO] Extention of input filepath:", extension))
    flag.ext <- TRUE

    if (extension == "yaml") {
      flow <- input.filepath %>% tidycwl::read_cwl(format = "yaml")
      cwl.version <- flow$cwlVersion
      if(str_detect(cwl.version, "v1\\.\\d*|sbg:draft-2")){
        flag.cwl <- TRUE
      }
    }
    if (str_detect(extension, "json|cwl")) {
      flow <- input.filepath %>% tidycwl::read_cwl(format = "json")
      cwl.version <- flow$cwlVersion
      if(!is.null(cwl.version)){
        if(str_detect(cwl.version, "v1\\.\\d*|sbg:draft-2")){
          flag.cwl <- TRUE
        }
      }
    }

  }else{
    return(shinyalert('Unsupported File Type', "That filetype is not supported by the BCO app. Please select a .cwl, .yaml, or .json file.", type = 'error'))
  }

  if (flag.ext & flag.cwl == T) {
    return(TRUE)
  }else{
    return(FALSE)
  }
}

#Prevent user from uploading a bco.json file which is generated by the app but not with same use as .json
observeEvent(input$upfile_local_composer, {

  if(str_detect(input$upfile_local_composer$name, 'bco.json') == T){
    return(shinyalert('Unsupported File Type', "That filetype is not supported by the BCO app. Please select a .cwl, .yaml, or .json file.", type = 'error'))
  }

  inputcheck(input$upfile_local_composer$datapath)

}, ignoreNULL = T, ignoreInit = T)

# get raw cwl
get_rawcwl_local <- eventReactive(input$upfile_local_composer, {
  cwl_out <- get_cwl_local(input$upfile_local_composer$datapath, format = file_ext(input$upfile_local_composer$datapath))
  cwl_out
})

#
# observeEvent(input$upfile_local_composer$datapath, {enable("btn_upfile_local_composer")})
